import { ref, uploadBytes, getDownloadURL } from 'firebase/storage';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { storage, db } from './firebase';

export async function uploadPhoto(
  tripId: string,
  userId: string,
  uri: string,
  caption: string,
  location: { latitude: number; longitude: number; altitude: number }
) {
  const response = await fetch(uri);
  const blob = await response.blob();

  const filename = `trips/${tripId}/photos/${Date.now()}.jpg`;
  const storageRef = ref(storage, filename);
  await uploadBytes(storageRef, blob);

  const imageURL = await getDownloadURL(storageRef);

  const photosRef = collection(db, 'trips', tripId, 'photos');
  await addDoc(photosRef, {
    userId,
    imageURL,
    thumbnailURL: '', // Generated by Cloud Function
    caption,
    location,
    takenAt: serverTimestamp(),
    uploadedAt: serverTimestamp(),
  });

  return imageURL;
}
